name: Export Solution

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions

jobs:
  build:

    runs-on: windows-latest   # alternate runner OS is: ubuntu-latest

    steps:
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{ secrets.DATAVERSE_URL }}
        app-id: ${{ secrets.APPLICATION_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        solution-name: CompanyInfoFinderMaxTest
        solution-output-file: 'CompanyInfoFinderMaxTest.zip'
        working-directory: 'out'

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: 'out/CompanyInfoFinderMaxTest1.zip'
        solution-folder: 'out/solutions/CompanyInfoFinderMaxTest one'
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Publish Solution
      uses: microsoft/powerplatform-actions/publish-solution@v1
      with:
        environment-url: ${{ secrets.DATAVERSE_URL }}
        app-id: ${{ secrets.APPLICATION_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}

    - name: Prepare solution changes for check-in into source control
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: 'out/solutions/CompanyInfoFinderMaxTest one'
        solution-target-folder: 'src/solutions/solution1'
        token: ${{ secrets.GITHUB_TOKEN }}
